package com.codeworkdigital.api.processanalysis.application;

public enum TechnologyFitReasonCode {
    OBSERVED_STAGE,
    INFERRED_STAGE,
    OPERATION_IS_INTERPRETATION,
    OPERATION_IS_LOOKUP,
    OPERATION_IS_CALCULATION,
    OPERATION_IS_DECISION,
    OPERATION_IS_APPROVAL,
    INPUT_IS_UNSTRUCTURED,
    INPUT_IS_STRUCTURED,
    DETERMINISTIC_RULES_LIKELY_SUFFICIENT,
    SYSTEM_ACCESS_PATTERN_SUGGESTS_INTEGRATION,
    AVAILABLE_EVIDENCE_IS_INSUFFICIENT
}
