CREATE TABLE contact_submission (
    id uuid NOT NULL,
    idempotency_key uuid NOT NULL,
    payload_hash varchar(64) NOT NULL,
    source varchar(32) NOT NULL,
    locale varchar(8) NOT NULL,
    name varchar(120) NOT NULL,
    email varchar(254) NOT NULL,
    phone varchar(40),
    company_or_project varchar(160),
    message varchar(4000) NOT NULL,
    status varchar(32) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT pk_contact_submission PRIMARY KEY (id),
    CONSTRAINT uq_contact_submission_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_contact_submission_payload_hash CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_contact_submission_source CHECK (source IN ('HOME', 'CONTACT_PAGE')),
    CONSTRAINT ck_contact_submission_locale CHECK (locale IN ('ES', 'EN', 'IT')),
    CONSTRAINT ck_contact_submission_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_contact_submission_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT ck_contact_submission_phone_not_blank CHECK (phone IS NULL OR btrim(phone) <> ''),
    CONSTRAINT ck_contact_submission_company_or_project_not_blank CHECK (company_or_project IS NULL OR btrim(company_or_project) <> ''),
    CONSTRAINT ck_contact_submission_message_not_blank CHECK (btrim(message) <> ''),
    CONSTRAINT ck_contact_submission_status CHECK (status IN ('RECEIVED')),
    CONSTRAINT ck_contact_submission_updated_at_not_before_created_at CHECK (updated_at >= created_at)
);
